# Taskfile (See https://taskfile.dev)

version: "3"

vars:
  # The project version
  VERSION: "0.0.3"

  # The current short Git commit hash
  COMMIT:
    sh: git rev-parse --short HEAD

  # The current Git branch
  BRANCH:
    sh: git rev-parse --abbrev-ref HEAD

  # The current timestamp
  TIMESTAMP:
    sh: date --iso-8601=seconds --utc

  # Cargo target
  CARGO_TARGET:
    sh: rustup show active-toolchain | grep -Po "^[^-]+-\K\S+"

  # Cargo build profile
  CARGO_PROFILE: dev

  # Library bultiarch triplet
  LIB_MULTIARCH_TRIPLET:
    sh: gcc -dumpmachine

tasks:
  build:
    desc: Build the project
    label: 'Build the project ({{ list .CARGO_TARGET .CARGO_PROFILE | join "|" | sha256sum }})'
    cmds:
      - cargo build --target={{ .CARGO_TARGET }} --profile={{ .CARGO_PROFILE }}
    sources:
      - ./crates/**/*
    generates:
      - target/**/*

  link-lib:
    desc: Link the PAM library for testing purposes
    label: Link the PAM library ({{ .LIB_MULTIARCH_TRIPLET | sha256sum }})
    cmds:
      - sudo ln --force --symbolic "{{ joinPath .TASKFILE_DIR "target" .CARGO_TARGET .BUILD_DIR_NAME "libpam_oauth.so" }}" "/usr/lib/{{ .LIB_MULTIARCH_TRIPLET }}/security/pam_oauth.so"
    vars:
      BUILD_DIR_NAME: |
        {{- if or (eq .CARGO_PROFILE "dev") (eq .CARGO_PROFILE "test") -}}
          debug
        {{- else -}}
          release
        {{- end -}}
    deps:
      - build

  lint:
    desc: Lint the project
    cmds:
      - cargo clippy

  package:
    desc: Package the project
    label: 'Package the project ({{ list .GOARCH .GOOS .LIB_MULTIARCH_TRIPLET .VERSION | join "|" | sha256sum }})'
    cmds:
      - mkdir -p ./dist/pkg
      - for:
          - deb
          - rpm
          - apk
          - archlinux
        cmd: nfpm pkg --config build/nfpm-client.yml --packager {{ .ITEM }} --target ./dist/pkg/
      - for:
          - deb
          - rpm
          - apk
          - archlinux
        cmd: nfpm pkg --config build/nfpm-server.yml --packager {{ .ITEM }} --target ./dist/pkg/
    env:
      GOARCH: "{{ .GOARCH }}"
      GOOS: "{{ .GOOS }}"
      LIB_MULTIARCH_TRIPLET: "{{ .LIB_MULTIARCH_TRIPLET }}"
      SIGNING_KEY_FILE: ./signing.key
      SIGNING_KEY_ID: 0x00000000
      VERSION: "{{ .VERSION }}"
    deps:
      - build

  clean:
    desc: Clean the project
    cmds:
      - cargo clean
    sources:
      - target/**/*

  generate:grpc:
    desc: Generate the gRPC code
    cmds:
      - protoc --go_out=. --go_opt=paths=import --go-grpc_out=. --go-grpc_opt=paths=import ./api/grpc.proto
    sources:
      - ./api/grpc.proto
    # generates:
    #   - TODO