// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: api/grpc.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	// Issue a challenge for the user to verify its identity
	IssueChallenge(ctx context.Context, in *IssueChallengeRequest, opts ...grpc.CallOption) (*IssueChallengeResponse, error)
	// Verify a challenge
	VerifyChallenge(ctx context.Context, in *VerifyChallengeRequest, opts ...grpc.CallOption) (*VerifyChallengeResponse, error)
	// Get challenge information
	GetChallengeInfo(ctx context.Context, in *GetChallengeInfoRequest, opts ...grpc.CallOption) (*GetChallengeInfoResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) IssueChallenge(ctx context.Context, in *IssueChallengeRequest, opts ...grpc.CallOption) (*IssueChallengeResponse, error) {
	out := new(IssueChallengeResponse)
	err := c.cc.Invoke(ctx, "/AuthService/IssueChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyChallenge(ctx context.Context, in *VerifyChallengeRequest, opts ...grpc.CallOption) (*VerifyChallengeResponse, error) {
	out := new(VerifyChallengeResponse)
	err := c.cc.Invoke(ctx, "/AuthService/VerifyChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetChallengeInfo(ctx context.Context, in *GetChallengeInfoRequest, opts ...grpc.CallOption) (*GetChallengeInfoResponse, error) {
	out := new(GetChallengeInfoResponse)
	err := c.cc.Invoke(ctx, "/AuthService/GetChallengeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility
type AuthServiceServer interface {
	// Issue a challenge for the user to verify its identity
	IssueChallenge(context.Context, *IssueChallengeRequest) (*IssueChallengeResponse, error)
	// Verify a challenge
	VerifyChallenge(context.Context, *VerifyChallengeRequest) (*VerifyChallengeResponse, error)
	// Get challenge information
	GetChallengeInfo(context.Context, *GetChallengeInfoRequest) (*GetChallengeInfoResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (UnimplementedAuthServiceServer) IssueChallenge(context.Context, *IssueChallengeRequest) (*IssueChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueChallenge not implemented")
}
func (UnimplementedAuthServiceServer) VerifyChallenge(context.Context, *VerifyChallengeRequest) (*VerifyChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyChallenge not implemented")
}
func (UnimplementedAuthServiceServer) GetChallengeInfo(context.Context, *GetChallengeInfoRequest) (*GetChallengeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChallengeInfo not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_IssueChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).IssueChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/IssueChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).IssueChallenge(ctx, req.(*IssueChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/VerifyChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyChallenge(ctx, req.(*VerifyChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetChallengeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChallengeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetChallengeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/GetChallengeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetChallengeInfo(ctx, req.(*GetChallengeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueChallenge",
			Handler:    _AuthService_IssueChallenge_Handler,
		},
		{
			MethodName: "VerifyChallenge",
			Handler:    _AuthService_VerifyChallenge_Handler,
		},
		{
			MethodName: "GetChallengeInfo",
			Handler:    _AuthService_GetChallengeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc.proto",
}
