// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: api/grpc.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for IssueChallenge method
type IssueChallengeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Username of the user the challenge is being issued for
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *IssueChallengeRequest) Reset() {
	*x = IssueChallengeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssueChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueChallengeRequest) ProtoMessage() {}

func (x *IssueChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueChallengeRequest.ProtoReflect.Descriptor instead.
func (*IssueChallengeRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *IssueChallengeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Response message for IssueChallenge method
type IssueChallengeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Arbitrary identifier for the challenge
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The challenge URL
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *IssueChallengeResponse) Reset() {
	*x = IssueChallengeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssueChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueChallengeResponse) ProtoMessage() {}

func (x *IssueChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueChallengeResponse.ProtoReflect.Descriptor instead.
func (*IssueChallengeResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *IssueChallengeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IssueChallengeResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Request message for VerifyChallenge method
type VerifyChallengeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identifier of the challenge to verify
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Verification code sent to the user after completing the OAuth flow to verify the user
	// attempting to login via the PAM module is the same user that completed the OAuth flow
	VerificationCode string `protobuf:"bytes,2,opt,name=verificationCode,proto3" json:"verificationCode,omitempty"`
}

func (x *VerifyChallengeRequest) Reset() {
	*x = VerifyChallengeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyChallengeRequest) ProtoMessage() {}

func (x *VerifyChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyChallengeRequest.ProtoReflect.Descriptor instead.
func (*VerifyChallengeRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyChallengeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VerifyChallengeRequest) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

// Response message for VerifyChallenge method
type VerifyChallengeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Whether the challenge was verified successfully
	Verified bool `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
}

func (x *VerifyChallengeResponse) Reset() {
	*x = VerifyChallengeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyChallengeResponse) ProtoMessage() {}

func (x *VerifyChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyChallengeResponse.ProtoReflect.Descriptor instead.
func (*VerifyChallengeResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyChallengeResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

// Request message for GetChallengeInfo method
type GetChallengeInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identifier of the challenge to get info for
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetChallengeInfoRequest) Reset() {
	*x = GetChallengeInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChallengeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeInfoRequest) ProtoMessage() {}

func (x *GetChallengeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetChallengeInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *GetChallengeInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response message for GetChallengeInfo method
type GetChallengeInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Environment variables for the challenge
	Env map[string]string `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Username of the user the challenge is for
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *GetChallengeInfoResponse) Reset() {
	*x = GetChallengeInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChallengeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeInfoResponse) ProtoMessage() {}

func (x *GetChallengeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetChallengeInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *GetChallengeInfoResponse) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *GetChallengeInfoResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_api_grpc_proto protoreflect.FileDescriptor

var file_api_grpc_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x33, 0x0a, 0x15, 0x49, 0x73, 0x73, 0x75, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x16, 0x49, 0x73, 0x73, 0x75, 0x65, 0x43, 0x68,
	0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x22, 0x54, 0x0a, 0x16, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x68, 0x61, 0x6c, 0x6c,
	0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x35, 0x0a, 0x17, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0x29,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa4, 0x01, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e,
	0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45,
	0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x36, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x32, 0xdf, 0x01, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x41, 0x0a, 0x0e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e,
	0x67, 0x65, 0x12, 0x16, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65,
	0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x49, 0x73, 0x73,
	0x75, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x68, 0x61,
	0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61,
	0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_grpc_proto_rawDescOnce sync.Once
	file_api_grpc_proto_rawDescData = file_api_grpc_proto_rawDesc
)

func file_api_grpc_proto_rawDescGZIP() []byte {
	file_api_grpc_proto_rawDescOnce.Do(func() {
		file_api_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_proto_rawDescData)
	})
	return file_api_grpc_proto_rawDescData
}

var file_api_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_grpc_proto_goTypes = []interface{}{
	(*IssueChallengeRequest)(nil),    // 0: IssueChallengeRequest
	(*IssueChallengeResponse)(nil),   // 1: IssueChallengeResponse
	(*VerifyChallengeRequest)(nil),   // 2: VerifyChallengeRequest
	(*VerifyChallengeResponse)(nil),  // 3: VerifyChallengeResponse
	(*GetChallengeInfoRequest)(nil),  // 4: GetChallengeInfoRequest
	(*GetChallengeInfoResponse)(nil), // 5: GetChallengeInfoResponse
	nil,                              // 6: GetChallengeInfoResponse.EnvEntry
}
var file_api_grpc_proto_depIdxs = []int32{
	6, // 0: GetChallengeInfoResponse.env:type_name -> GetChallengeInfoResponse.EnvEntry
	0, // 1: AuthService.IssueChallenge:input_type -> IssueChallengeRequest
	2, // 2: AuthService.VerifyChallenge:input_type -> VerifyChallengeRequest
	4, // 3: AuthService.GetChallengeInfo:input_type -> GetChallengeInfoRequest
	1, // 4: AuthService.IssueChallenge:output_type -> IssueChallengeResponse
	3, // 5: AuthService.VerifyChallenge:output_type -> VerifyChallengeResponse
	5, // 6: AuthService.GetChallengeInfo:output_type -> GetChallengeInfoResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_grpc_proto_init() }
func file_api_grpc_proto_init() {
	if File_api_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IssueChallengeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IssueChallengeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyChallengeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyChallengeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChallengeInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChallengeInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_proto_goTypes,
		DependencyIndexes: file_api_grpc_proto_depIdxs,
		MessageInfos:      file_api_grpc_proto_msgTypes,
	}.Build()
	File_api_grpc_proto = out.File
	file_api_grpc_proto_rawDesc = nil
	file_api_grpc_proto_goTypes = nil
	file_api_grpc_proto_depIdxs = nil
}
