# Create a release when a new tag is pushed
name: release
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Install apt dependencies
        run: sudo apt install -y libpam0g libpam0g-dev gcc-aarch64-linux-gnu

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Setup nfpm
        run: go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest

      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and package for native
        run: task package

      - name: Build and package for ARM64
        run: task package CC="aarch64-linux-gnu-gcc" GOARCH="arm64" GOOS="linux" MULTIARCH_TRIPLET="aarch64-linux-gnu"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/pkg/*